// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-me.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-me.ts
var get_me_default = defineTool({
  name: "get_me",
  title: "Get my profile",
  description: "Return the signed-in Apnea Mate user's profile: name, bio, location, freediving experience.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("profiles").select("name,last_name,bio,location,freediving_since,has_insurance,email,avatar_url").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-upcoming-sessions.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
var list_upcoming_sessions_default = defineTool2({
  name: "list_upcoming_sessions",
  title: "List my upcoming sessions",
  description: "List Apnea Mate sessions the signed-in user has joined (as organizer or participant) that are scheduled in the future.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max sessions to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const nowIso = (/* @__PURE__ */ new Date()).toISOString();
    const { data: parts, error: partsErr } = await sb.from("session_participants").select("session_id").eq("user_id", userId).is("cancelled_at", null);
    if (partsErr) return { content: [{ type: "text", text: partsErr.message }], isError: true };
    const joinedIds = (parts ?? []).map((p) => p.session_id);
    let query = sb.from("sessions").select("id,title,date_time,duration_minutes,session_type,level,is_paid,spot_id,group_id,creator_id,status").gte("date_time", nowIso).order("date_time", { ascending: true }).limit(limit ?? 20);
    if (joinedIds.length > 0) {
      query = query.or(`creator_id.eq.${userId},id.in.(${joinedIds.join(",")})`);
    } else {
      query = query.eq("creator_id", userId);
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { sessions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-spots.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var search_spots_default = defineTool3({
  name: "search_spots",
  title: "Search dive spots",
  description: "Search Apnea Mate dive spots by name or location substring. Returns spot metadata including coordinates and environment type.",
  inputSchema: {
    query: z2.string().trim().min(1).describe("Text to match against spot name or location."),
    limit: z2.number().int().min(1).max(50).optional().describe("Max spots to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const like = `%${query.replace(/[%_]/g, "")}%`;
    const { data, error } = await supabaseForUser(ctx).from("spots").select("id,name,location,environment_type,latitude,longitude,description").or(`name.ilike.${like},location.ilike.${like}`).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { spots: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-groups.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
var list_my_groups_default = defineTool4({
  name: "list_my_groups",
  title: "List my groups",
  description: "List Apnea Mate groups the signed-in user is a member of.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data: memberships, error: mErr } = await sb.from("group_members").select("group_id,role").eq("user_id", ctx.getUserId());
    if (mErr) return { content: [{ type: "text", text: mErr.message }], isError: true };
    const ids = (memberships ?? []).map((m) => m.group_id);
    if (ids.length === 0) {
      return { content: [{ type: "text", text: "[]" }], structuredContent: { groups: [] } };
    }
    const { data, error } = await sb.from("groups").select("id,name,description,group_type,activity_type,location,verified").in("id", ids);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { groups: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vjvhaegbfjepysptcygz";
var mcp_default = defineMcp({
  name: "apnea-mate-mcp",
  title: "Apnea Mate",
  version: "0.1.0",
  instructions: "Tools for Apnea Mate, a freediving community app. Use `get_me` for the signed-in user's profile, `list_upcoming_sessions` for their upcoming dive sessions, `search_spots` to find dive spots by name or location, and `list_my_groups` for the groups they belong to.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_me_default, list_upcoming_sessions_default, search_spots_default, list_my_groups_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
